---

 - name: 'MySQL config file'
   vars:
     innodb_buffer_pool_size: 125M
   template: 
     src: my.cnf.j2 
     dest: /etc/mysql/mysql.conf.d/mysqld.cnf
   tags: 
   - mysql
   - mysql_config
   - mysql2

 - name: 'Restart MySQL'
   service: name=mysql state=restarted
   tags: 
   - mysql
   - mysql_config
   - mysql2
