---

 - name: Update MySQL password for all {{ mysql_rootuser }} accounts
   mysql_user: 
     name: "{{ mysql_root_user }}"
     host: "{{ item }}" 
     password: "{{ mysql_root_password }}"
     priv: '*.*:ALL,GRANT'
     check_implicit_admin: yes
     login_user: "{{ mysql_root_user }}"
     login_password: "{{ mysql_root_password }}"         
     state: present
   with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost     
   tags: mysql
 
 - name: users | add root credentials
   template: 
     src: common/my.user.cnf.j2
     dest: /root/.my.cnf
     owner: root
     mode: 0600
   notify:
     - mysql-restart

 - name: users | add user credentials
   template: 
     src: common/my.user.cnf.j2
     dest: ~/.my.cnf
     owner: "{{ ansible_env.USER }}"
     mode: 0600
   notify:
     - mysql-restart

 - name: Update MySQL password for all {{ mysql_user }} accounts
   mysql_user: 
     name: "{{ test }}_{{ item.databaseuser }}"
     host: localhost
     password: "{{ item.databasepass }}"
     priv: '*.*:ALL,GRANT'
     state: present
   with_items: "{{ route }}"
   tags: mysql

 - name: Update MySQL password for all {{ mysql_user }} accounts
   mysql_user: 
     name: "{{ test }}_{{ item.databaseuser }}"
     host: "%"
     password: "{{ item.databasepass }}"
     priv: '*.*:ALL,GRANT'
     state: present
   with_items: "{{ route }}"
   tags: mysql   
   
 - name: Create a new {{ test }} database user with name 
   mysql_db:
     name: '{{ test }}_{{ item.database }}'
     state: present
   with_items: "{{ route }}"
   tags: mysql   
   

 - name: Update MySQL password for all {{ mysql_user }} accounts
   mysql_user: 
     name: "{{ mysql_user }}"
     host: "{{ item }}" 
     password: "{{ mysql_devop_pass }}"
     priv: '*.*:ALL,GRANT'
     state: present
   with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost  
     - "%"     
   tags: mysql    

 - name: Copy the root credentials as .my.cnf file
   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
   tags: mysql
   
 - name: Removes all anonymous user accounts
   mysql_user:
     name: ''
     host: "{{ item }}"
     state: absent
   with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost     
   tags: mysql