---

 
    - name: PHP | Install Ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php' update_cache=yes
      tags: 
         - apache2
         - apache_phpondrej


    - name: install software-properties-common
      apt: name=software-properties-common update_cache=yes state=latest
      tags: 
         - apache2
         - apache_software-properties-common

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      tags: 
         - apache2
         - apache_install 

    - name: activate apache2 module
      apache2_module:
        state: present
        name: "{{item}}"
      notify:
        - restart apache2
      with_items: 
        - setenvif
        - rewrite
        - ssl    
        - expires
        - headers 
        - rewrite    
      tags: apache2

    - name: apache2 listen on port 80
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen 80" state=present
      notify:
        - restart apache2
      tags: apache2
      
    